# Generated by Django 3.0 on 2019-12-29 04:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('contacts', models.PositiveIntegerField()),
                ('contacts2', models.PositiveIntegerField()),
                ('profession', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profession_required', models.CharField(max_length=20)),
                ('task_title', models.CharField(max_length=100)),
                ('task_description', models.TextField(max_length=500)),
                ('date_posted', models.DateField(auto_now=True)),
                ('expiry_date', models.DateField()),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Actor')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=300)),
                ('actor', models.ForeignKey(on_delete=models.SET(True), to='books.Actor')),
                ('task', models.ForeignKey(on_delete=models.SET(True), to='books.Task')),
            ],
        ),
    ]
